# Generated by Django 2.0 on 2018-12-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selling_point',
            field=models.BooleanField(default=False),
        ),
    ]
