# Generated by Django 2.0 on 2018-12-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_cart_exist'),
    ]

    operations = [
        migrations.AddField(
            model_name='paraprofile',
            name='channel_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
