# Generated by Django 2.0 on 2019-01-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_paraprofile_channel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='province',
        ),
        migrations.RemoveField(
            model_name='paraprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='paraprofile',
            name='province',
        ),
        migrations.AddField(
            model_name='paraprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
