# Generated by Django 2.0 on 2018-12-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
