# Generated by Django 2.0 on 2018-12-23 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_auto_20181223_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 16, 11, 24, 34134, tzinfo=utc)),
        ),
    ]
