# Generated by Django 2.0 on 2018-12-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_auto_20181223_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
    ]
