# Generated by Django 2.0 on 2018-12-27 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_auto_20181223_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='para',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='account.ParaProfile'),
        ),
    ]
